/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AppModel } from "./AppModel";
import { AppModelCountArgs } from "./AppModelCountArgs";
import { AppModelFindManyArgs } from "./AppModelFindManyArgs";
import { AppModelFindUniqueArgs } from "./AppModelFindUniqueArgs";
import { CreateAppModelArgs } from "./CreateAppModelArgs";
import { UpdateAppModelArgs } from "./UpdateAppModelArgs";
import { DeleteAppModelArgs } from "./DeleteAppModelArgs";
import { CookieFindManyArgs } from "../../cookie/base/CookieFindManyArgs";
import { Cookie } from "../../cookie/base/Cookie";
import { User } from "../../user/base/User";
import { AppModelService } from "../appModel.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AppModel)
export class AppModelResolverBase {
  constructor(
    protected readonly service: AppModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "read",
    possession: "any",
  })
  async _appModelsMeta(
    @graphql.Args() args: AppModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AppModel])
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "read",
    possession: "any",
  })
  async appModels(
    @graphql.Args() args: AppModelFindManyArgs
  ): Promise<AppModel[]> {
    return this.service.appModels(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AppModel, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "read",
    possession: "own",
  })
  async appModel(
    @graphql.Args() args: AppModelFindUniqueArgs
  ): Promise<AppModel | null> {
    const result = await this.service.appModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AppModel)
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "create",
    possession: "any",
  })
  async createAppModel(
    @graphql.Args() args: CreateAppModelArgs
  ): Promise<AppModel> {
    return await this.service.createAppModel({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AppModel)
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "update",
    possession: "any",
  })
  async updateAppModel(
    @graphql.Args() args: UpdateAppModelArgs
  ): Promise<AppModel | null> {
    try {
      return await this.service.updateAppModel({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AppModel)
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "delete",
    possession: "any",
  })
  async deleteAppModel(
    @graphql.Args() args: DeleteAppModelArgs
  ): Promise<AppModel | null> {
    try {
      return await this.service.deleteAppModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Cookie], { name: "cookies" })
  @nestAccessControl.UseRoles({
    resource: "Cookie",
    action: "read",
    possession: "any",
  })
  async findCookies(
    @graphql.Parent() parent: AppModel,
    @graphql.Args() args: CookieFindManyArgs
  ): Promise<Cookie[]> {
    const results = await this.service.findCookies(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: AppModel): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
